In [4]:
import numpy as np
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10])
arr_2d = np.array([[3,4,1], [4,8,2], [2,99,4]])
print(arr_1d)
print(arr_2d)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 3  4  1]
 [ 4  8  2]
 [ 2 99  4]]


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])


arr_sum = arr.sum()
arr_mean = arr.mean()
arr_max = arr.max()

print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Max:", arr_max)


arr_times_two = arr * 2
print("Multiplied by 2:", arr_times_two)


arr_modified = arr.copy()
arr_modified[arr_modified > 5] = 0
print(arr_modified)


Sum: 55
Mean: 5.5
Max: 10
Multiplied by 2: [ 2  4  6  8 10 12 14 16 18 20]
[1 2 3 4 5 0 0 0 0 0]
